volumes:
  planit:
services:
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: eventsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test-databases
    ports:
      - 15432:5432

  events_service:
    build:
        context: ./events_service
        dockerfile: ./Dockerfile.dev
    ports:
        - "8001:8000"
    volumes:
      - ./sample_service:/app
    environment:
      DATABASE_URL: postgresql://planit:planit@db/planit
  db:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - planit:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: planit
      POSTGRES_USER: planit
      POSTGRES_DB: planit
    ports:
      - "15432:5432"

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
