volumes:
  planit:
services:
  fastapi:
    build:
      context: accounts_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./accounts_service:/app
    environment:
      # SIGNING_KEY:
      # WAIT_HOSTS: db:5432
      # WAIT_BEFORE: 5
      # WAIT_TIMEOUT: 60
      DATABASE_URL: postgresql://planit:planit@db/planit

  db:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - planit:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: planit
      POSTGRES_USER: planit
      POSTGRES_DB: planit
    ports:
      - "15432:5432"

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_ACCOUNTS_SERVICE_API_HOST: http://localhost:8000
